WarOfWords.Web/Controllers/LevelController.cs
using Microsoft.AspNetCore.Mvc;

namespace WorOfWords.Web.Controllers
{
    public class LevelController : Controller
    {
        public IActionResult All()
        {
            return View();
        }
    }
}

WarOfWords.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Война на думи - @ViewData["Title"]</title>
    <link href="~/css/all-files.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css">
</head>
<body>
    <div class="container" style="background-image: url('https://images.unsplash.com/photo-1457269449834-928af64c684d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1200&q=80')" ;>
        <header class="main-header">
            <ul class="navbar-main">
                <li>
                    <a asp-controller="Level" asp-action="All"><i class="fas fa-list-ul"></i> Нива</a>
                </li>
                <li>
                    <a asp-controller="Category" asp-action="All"><i class="fas fa-bars"></i> Категории</a>
                </li>
                <li>
                    <a asp-controller="Home" asp-action="AllUsers"><i class="fas fa-users"></i> Участници</a>
                </li>
            </ul>
            <ul class="navbar-login">
                @Html.Partial("~/Views/Shared/_LoginPartial.cshtml")
            </ul>
        </header>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>